[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brave-releases-checker"
version = "0.1.0"
authors = [
  { name="Your Name", email="your.email@example.com" },
]
description = "Checks for new Brave Browser releases"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "packaging",
    "distro",
]

[tool.setuptools.entry-points]
console_scripts = [
    "brave-releases-checker = brave_releases_checker.main:BraveReleaseChecker().run",
]

[project.data-files]
"brave_releases_checker" = ["config.ini"]